const bugs = {
    commonButterfly: {
        name:"Common Butterfly",
        picture: true,
        price:"160",
        location:"Flying",
        startTime:"4 am",
        endTime:"7 pm",
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: false,
        aug: false,
        sep: true,
        oct: true,
        nov: true,
        dev: true,
        notes:""
    },
    yellowButterfly: {
        name:"Yellow Butterfly",
        picture: true,
        price:"160",
        location:"Flying",
        startTime:"4 am",
        endTime:"7 pm",
        jan: false,
        feb: false,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: false,
        aug: false,
        sep: true,
        oct: true,
        nov: false,
        dev: false,
        notes:""
    },
    tigerButterfly: {
        name:"Tiger Butterfly",
        picture: true,
        price:"240",
        location:"Flying",
        startTime:"4 am",
        endTime:"7 pm",
        jan: false,
        feb: false,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: false,
        nov: false,
        dev: false,
        notes:""
    }
}
